var serverTemplates = {
    community: {
        name: 'Community / Chill Server',
        categories: [
            { name: 'WELCOME', channels: [
                { name: 'welcome', type: 'text', readOnly: true },
                { name: 'rules', type: 'text', readOnly: true },
                { name: 'self-roles', type: 'text', readOnly: true },
                { name: 'invites', type: 'text', readOnly: true },
            ]},
            { name: 'ANNOUNCEMENTS', channels: [
                { name: 'announcements', type: 'text', readOnly: true },
                { name: 'updates', type: 'text', readOnly: true },
                { name: 'changelogs', type: 'text', readOnly: true },
                { name: 'polls', type: 'text' },
            ]},
            { name: 'SUPPORT', channels: [
                { name: 'create-ticket', type: 'text' },
                { name: 'support', type: 'text' },
                { name: 'apply', type: 'text' },
            ]},
            { name: 'GENERAL', channels: [
                { name: 'chat', type: 'text' },
                { name: 'commands', type: 'text' },
                { name: 'media', type: 'text' },
                { name: 'poetry', type: 'text' },
                { name: 'pfp-wallpaper', type: 'text' },
            ]},
            { name: 'FUN ZONE', channels: [
                { name: 'owo', type: 'text' },
                { name: 'truth-or-dare', type: 'text' },
                { name: 'counting', type: 'text' },
                { name: 'memes', type: 'text' },
            ]},
            { name: 'VOICE CHANNELS', channels: [
                { name: 'music-commands', type: 'text' },
                { name: 'General', type: 'voice' },
                { name: 'Duo', type: 'voice' },
                { name: 'Music 1', type: 'voice' },
                { name: 'Music 2', type: 'voice' },
            ]},
            { name: 'STAFF AREA', channels: [
                { name: 'staff-chat', type: 'text', staffOnly: true },
                { name: 'staff-updates', type: 'text', staffOnly: true },
                { name: 'staff-commands', type: 'text', staffOnly: true },
                { name: 'staff-leave', type: 'text', staffOnly: true },
                { name: 'mod-logs', type: 'text', staffOnly: true },
                { name: 'ticket-logs', type: 'text', staffOnly: true },
            ]},
        ],
        roles: [
            { name: 'DIVIDER_STAFF', color: '#2B2D31', hoist: true, type: 'divider', divLabel: 'Staff' },
            { name: 'Owner', color: '#FF0000', hoist: true, type: 'owner' },
            { name: 'Co-Owner', color: '#FF4500', hoist: true, type: 'coowner' },
            { name: 'Chief Admin', color: '#E74C3C', hoist: true, type: 'chief_admin' },
            { name: 'Admin', color: '#E74C3C', hoist: true, type: 'admin' },
            { name: 'Head Mod', color: '#E67E22', hoist: true, type: 'headmod' },
            { name: 'Moderator', color: '#3498DB', hoist: true, type: 'mod' },
            { name: 'Trial Mod', color: '#5DADE2', hoist: true, type: 'trialmod' },
            { name: 'Staff', color: '#9B59B6', hoist: true, type: 'staff' },
            { name: 'Developer', color: '#E91E63', hoist: true, type: 'dev' },
            { name: 'Support', color: '#2ECC71', hoist: true, type: 'support' },
            { name: 'DIVIDER_SPECIAL', color: '#2B2D31', hoist: true, type: 'divider2', divLabel: 'Special' },
            { name: 'Partner', color: '#1ABC9C', hoist: true, type: 'partner' },
            { name: 'Booster', color: '#F47FFF', hoist: true, type: 'booster' },
            { name: 'MVP', color: '#F1C40F', hoist: true, type: 'mvp' },
            { name: 'VIP', color: '#E67E22', hoist: true, type: 'vip' },
            { name: 'OG Member', color: '#FFD700', hoist: true, type: 'og' },
            { name: 'Active Chatter', color: '#2ECC71', hoist: true, type: 'active' },
            { name: 'DIVIDER_MEMBERS', color: '#2B2D31', hoist: true, type: 'divider3', divLabel: 'Members' },
            { name: 'Member', color: '#95A5A6', hoist: false, type: 'member' },
            { name: 'Atlas Bypass', color: '#2B2D31', hoist: false, type: 'bypass' },
            { name: 'Bots', color: '#546E7A', hoist: false, type: 'bots' },
        ]
    },
    gaming: {
        name: 'Gaming Server',
        categories: [
            { name: 'INFORMATION', channels: [
                { name: 'welcome', type: 'text', readOnly: true },
                { name: 'rules', type: 'text', readOnly: true },
                { name: 'self-roles', type: 'text', readOnly: true },
                { name: 'invites', type: 'text', readOnly: true },
            ]},
            { name: 'NEWS', channels: [
                { name: 'announcements', type: 'text', readOnly: true },
                { name: 'updates', type: 'text', readOnly: true },
                { name: 'events', type: 'text', readOnly: true },
                { name: 'giveaways', type: 'text' },
            ]},
            { name: 'CHAT', channels: [
                { name: 'general', type: 'text' },
                { name: 'off-topic', type: 'text' },
                { name: 'memes', type: 'text' },
                { name: 'clips', type: 'text' },
                { name: 'media', type: 'text' },
            ]},
            { name: 'GAMES', channels: [
                { name: 'valorant', type: 'text' },
                { name: 'fortnite', type: 'text' },
                { name: 'minecraft', type: 'text' },
                { name: 'gta', type: 'text' },
                { name: 'roblox', type: 'text' },
                { name: 'other-games', type: 'text' },
                { name: 'find-teammates', type: 'text' },
            ]},
            { name: 'FUN', channels: [
                { name: 'bot-commands', type: 'text' },
                { name: 'counting', type: 'text' },
                { name: 'truth-or-dare', type: 'text' },
            ]},
            { name: 'VOICE', channels: [
                { name: 'music-commands', type: 'text' },
                { name: 'General', type: 'voice' },
                { name: 'Gaming 1', type: 'voice' },
                { name: 'Gaming 2', type: 'voice' },
                { name: 'Ranked', type: 'voice' },
                { name: 'Music', type: 'voice' },
                { name: 'AFK', type: 'voice' },
            ]},
            { name: 'TICKETS', channels: [
                { name: 'create-ticket', type: 'text' },
            ]},
            { name: 'STAFF', channels: [
                { name: 'staff-chat', type: 'text', staffOnly: true },
                { name: 'staff-commands', type: 'text', staffOnly: true },
                { name: 'ticket-logs', type: 'text', staffOnly: true },
                { name: 'mod-logs', type: 'text', staffOnly: true },
            ]},
        ],
        roles: [
            { name: 'DIVIDER_STAFF', color: '#2B2D31', hoist: true, type: 'divider', divLabel: 'Staff' },
            { name: 'Owner', color: '#FF0000', hoist: true, type: 'owner' },
            { name: 'Co-Owner', color: '#FF4500', hoist: true, type: 'coowner' },
            { name: 'Admin', color: '#E74C3C', hoist: true, type: 'admin' },
            { name: 'Head Mod', color: '#E67E22', hoist: true, type: 'headmod' },
            { name: 'Moderator', color: '#3498DB', hoist: true, type: 'mod' },
            { name: 'Trial Mod', color: '#5DADE2', hoist: true, type: 'trialmod' },
            { name: 'Event Manager', color: '#9B59B6', hoist: true, type: 'staff' },
            { name: 'Support', color: '#2ECC71', hoist: true, type: 'support' },
            { name: 'DIVIDER_RANKS', color: '#2B2D31', hoist: true, type: 'divider2', divLabel: 'Ranks' },
            { name: 'Streamer', color: '#E91E63', hoist: true, type: 'streamer' },
            { name: 'Booster', color: '#F47FFF', hoist: true, type: 'booster' },
            { name: 'MVP', color: '#F1C40F', hoist: true, type: 'mvp' },
            { name: 'OG', color: '#FFD700', hoist: true, type: 'og' },
            { name: 'DIVIDER_MEMBERS', color: '#2B2D31', hoist: true, type: 'divider3', divLabel: 'Community' },
            { name: 'Gamer', color: '#2ECC71', hoist: false, type: 'member' },
            { name: 'Atlas Bypass', color: '#2B2D31', hoist: false, type: 'bypass' },
            { name: 'Bots', color: '#546E7A', hoist: false, type: 'bots' },
        ]
    },
    minecraft: {
        name: 'Minecraft Server',
        categories: [
            { name: 'SPAWN', channels: [
                { name: 'welcome', type: 'text', readOnly: true },
                { name: 'rules', type: 'text', readOnly: true },
                { name: 'server-ip', type: 'text', readOnly: true },
                { name: 'voting', type: 'text', readOnly: true },
            ]},
            { name: 'NEWS', channels: [
                { name: 'announcements', type: 'text', readOnly: true },
                { name: 'changelogs', type: 'text', readOnly: true },
                { name: 'server-status', type: 'text', readOnly: true },
            ]},
            { name: 'COMMUNITY', channels: [
                { name: 'general', type: 'text' },
                { name: 'screenshots', type: 'text' },
                { name: 'builds', type: 'text' },
                { name: 'trading', type: 'text' },
                { name: 'suggestions', type: 'text' },
            ]},
            { name: 'GAMEMODES', channels: [
                { name: 'survival', type: 'text' },
                { name: 'skyblock', type: 'text' },
                { name: 'pvp', type: 'text' },
                { name: 'creative', type: 'text' },
            ]},
            { name: 'SUPPORT', channels: [
                { name: 'create-ticket', type: 'text' },
                { name: 'bug-reports', type: 'text' },
                { name: 'player-reports', type: 'text' },
            ]},
            { name: 'VOICE', channels: [
                { name: 'General', type: 'voice' },
                { name: 'Gaming', type: 'voice' },
                { name: 'Staff', type: 'voice' },
            ]},
            { name: 'STAFF', channels: [
                { name: 'staff-chat', type: 'text', staffOnly: true },
                { name: 'staff-commands', type: 'text', staffOnly: true },
                { name: 'punishments', type: 'text', staffOnly: true },
                { name: 'mod-logs', type: 'text', staffOnly: true },
            ]},
        ],
        roles: [
            { name: 'DIVIDER_STAFF', color: '#2B2D31', hoist: true, type: 'divider', divLabel: 'Team' },
            { name: 'Owner', color: '#FF0000', hoist: true, type: 'owner' },
            { name: 'Co-Owner', color: '#FF4500', hoist: true, type: 'coowner' },
            { name: 'Admin', color: '#E74C3C', hoist: true, type: 'admin' },
            { name: 'Sr. Mod', color: '#E67E22', hoist: true, type: 'headmod' },
            { name: 'Moderator', color: '#3498DB', hoist: true, type: 'mod' },
            { name: 'Helper', color: '#2ECC71', hoist: true, type: 'staff' },
            { name: 'Builder', color: '#9B59B6', hoist: true, type: 'builder' },
            { name: 'Developer', color: '#E91E63', hoist: true, type: 'dev' },
            { name: 'Support', color: '#1ABC9C', hoist: true, type: 'support' },
            { name: 'DIVIDER_RANKS', color: '#2B2D31', hoist: true, type: 'divider2', divLabel: 'Players' },
            { name: 'Player', color: '#95A5A6', hoist: false, type: 'member' },
            { name: 'Atlas Bypass', color: '#2B2D31', hoist: false, type: 'bypass' },
            { name: 'Bots', color: '#546E7A', hoist: false, type: 'bots' },
        ]
    },
    hosting: {
        name: 'Hosting Server',
        categories: [
            { name: 'INFO', channels: [
                { name: 'welcome', type: 'text', readOnly: true },
                { name: 'rules', type: 'text', readOnly: true },
                { name: 'pricing', type: 'text', readOnly: true },
                { name: 'self-roles', type: 'text', readOnly: true },
            ]},
            { name: 'STATUS', channels: [
                { name: 'announcements', type: 'text', readOnly: true },
                { name: 'server-status', type: 'text', readOnly: true },
                { name: 'changelogs', type: 'text', readOnly: true },
                { name: 'maintenance', type: 'text', readOnly: true },
            ]},
            { name: 'GENERAL', channels: [
                { name: 'chat', type: 'text' },
                { name: 'commands', type: 'text' },
                { name: 'media', type: 'text' },
                { name: 'reviews', type: 'text' },
            ]},
            { name: 'SUPPORT', channels: [
                { name: 'create-ticket', type: 'text' },
                { name: 'faq', type: 'text', readOnly: true },
            ]},
            { name: 'VOICE', channels: [
                { name: 'General', type: 'voice' },
                { name: 'Support', type: 'voice' },
            ]},
            { name: 'STAFF', channels: [
                { name: 'staff-chat', type: 'text', staffOnly: true },
                { name: 'staff-commands', type: 'text', staffOnly: true },
                { name: 'ticket-logs', type: 'text', staffOnly: true },
                { name: 'mod-logs', type: 'text', staffOnly: true },
            ]},
        ],
        roles: [
            { name: 'DIVIDER_STAFF', color: '#2B2D31', hoist: true, type: 'divider', divLabel: 'Staff' },
            { name: 'Owner', color: '#FF0000', hoist: true, type: 'owner' },
            { name: 'Co-Owner', color: '#FF4500', hoist: true, type: 'coowner' },
            { name: 'Admin', color: '#E74C3C', hoist: true, type: 'admin' },
            { name: 'Developer', color: '#E91E63', hoist: true, type: 'dev' },
            { name: 'Moderator', color: '#3498DB', hoist: true, type: 'mod' },
            { name: 'Support', color: '#2ECC71', hoist: true, type: 'support' },
            { name: 'DIVIDER_USERS', color: '#2B2D31', hoist: true, type: 'divider2', divLabel: 'Users' },
            { name: 'Customer', color: '#1ABC9C', hoist: true, type: 'vip' },
            { name: 'Member', color: '#95A5A6', hoist: false, type: 'member' },
            { name: 'Atlas Bypass', color: '#2B2D31', hoist: false, type: 'bypass' },
            { name: 'Bots', color: '#546E7A', hoist: false, type: 'bots' },
        ]
    },
    selling: {
        name: 'Selling / Services Server',
        categories: [
            { name: 'SPAWN', channels: [
                { name: 'welcome', type: 'text', readOnly: true },
                { name: 'about-us', type: 'text', readOnly: true },
                { name: 'self-roles', type: 'text', readOnly: true },
            ]},
            { name: 'NOTES', channels: [
                { name: 'announcements', type: 'text', readOnly: true },
                { name: 'server-updates', type: 'text', readOnly: true },
                { name: 'partnerships', type: 'text', readOnly: true },
                { name: 'giveaways', type: 'text' },
            ]},
            { name: 'EXTRA', channels: [
                { name: 'pay-out', type: 'text' },
                { name: 'booster-perks', type: 'text', readOnly: true },
                { name: 'events', type: 'text' },
            ]},
            { name: 'COMMUNITY', channels: [
                { name: 'chit-chat', type: 'text' },
                { name: 'media', type: 'text' },
                { name: 'commands', type: 'text' },
                { name: 'server-bump', type: 'text' },
            ]},
            { name: 'SERVICES', channels: [
                { name: 'restock', type: 'text' },
                { name: 'methods', type: 'text' },
                { name: 'nitro', type: 'text' },
                { name: 'dev-services', type: 'text' },
                { name: 'games', type: 'text' },
            ]},
            { name: 'FREELANCER', channels: [
                { name: 'thumbnails', type: 'text' },
                { name: 'editing', type: 'text' },
                { name: 'content', type: 'text' },
                { name: 'sponsor', type: 'text' },
            ]},
            { name: 'VOICE', channels: [
                { name: 'General', type: 'voice' },
                { name: 'Duo', type: 'voice' },
                { name: 'Trio', type: 'voice' },
                { name: 'Squad', type: 'voice' },
            ]},
            { name: 'MUSIC', channels: [
                { name: 'music-dump', type: 'text' },
                { name: 'Music 1', type: 'voice' },
                { name: 'Music 2', type: 'voice' },
            ]},
            { name: 'STATION', channels: [
                { name: 'create-ticket', type: 'text' },
                { name: 'staff-apply', type: 'text' },
            ]},
            { name: 'STAFF', channels: [
                { name: 'staff-chat', type: 'text', staffOnly: true },
                { name: 'staff-commands', type: 'text', staffOnly: true },
                { name: 'ticket-logs', type: 'text', staffOnly: true },
                { name: 'mod-logs', type: 'text', staffOnly: true },
            ]},
        ],
        roles: [
            { name: 'DIVIDER_STAFF', color: '#2B2D31', hoist: true, type: 'divider', divLabel: 'Staff' },
            { name: 'Owner', color: '#FF0000', hoist: true, type: 'owner' },
            { name: 'Co-Owner', color: '#FF4500', hoist: true, type: 'coowner' },
            { name: 'Developer', color: '#E91E63', hoist: true, type: 'dev' },
            { name: 'Admin', color: '#E74C3C', hoist: true, type: 'admin' },
            { name: 'Moderator', color: '#3498DB', hoist: true, type: 'mod' },
            { name: 'Staff', color: '#9B59B6', hoist: true, type: 'staff' },
            { name: 'Support', color: '#2ECC71', hoist: true, type: 'support' },
            { name: 'DIVIDER_SPECIAL', color: '#2B2D31', hoist: true, type: 'divider2', divLabel: 'Special' },
            { name: 'Seller', color: '#1ABC9C', hoist: true, type: 'seller' },
            { name: 'Partner', color: '#1ABC9C', hoist: true, type: 'partner' },
            { name: 'Booster', color: '#F47FFF', hoist: true, type: 'booster' },
            { name: 'MVP', color: '#F1C40F', hoist: true, type: 'mvp' },
            { name: 'DIVIDER_MEMBERS', color: '#2B2D31', hoist: true, type: 'divider3', divLabel: 'Members' },
            { name: 'Member', color: '#95A5A6', hoist: false, type: 'member' },
            { name: 'Atlas Bypass', color: '#2B2D31', hoist: false, type: 'bypass' },
            { name: 'Bots', color: '#546E7A', hoist: false, type: 'bots' },
        ]
    },
    creator: {
        name: 'Content Creator Server',
        categories: [
            { name: 'HOME', channels: [
                { name: 'welcome', type: 'text', readOnly: true },
                { name: 'rules', type: 'text', readOnly: true },
                { name: 'self-roles', type: 'text', readOnly: true },
                { name: 'socials', type: 'text', readOnly: true },
            ]},
            { name: 'CONTENT', channels: [
                { name: 'announcements', type: 'text', readOnly: true },
                { name: 'uploads', type: 'text', readOnly: true },
                { name: 'live-now', type: 'text', readOnly: true },
                { name: 'giveaways', type: 'text' },
            ]},
            { name: 'COMMUNITY', channels: [
                { name: 'general', type: 'text' },
                { name: 'fan-art', type: 'text' },
                { name: 'memes', type: 'text' },
                { name: 'clips', type: 'text' },
                { name: 'suggestions', type: 'text' },
            ]},
            { name: 'SELF PROMO', channels: [
                { name: 'youtube', type: 'text' },
                { name: 'twitch', type: 'text' },
                { name: 'tiktok', type: 'text' },
            ]},
            { name: 'FUN', channels: [
                { name: 'bot-commands', type: 'text' },
                { name: 'counting', type: 'text' },
            ]},
            { name: 'VOICE', channels: [
                { name: 'General', type: 'voice' },
                { name: 'Collab', type: 'voice' },
                { name: 'Music', type: 'voice' },
            ]},
            { name: 'STAFF', channels: [
                { name: 'staff-chat', type: 'text', staffOnly: true },
                { name: 'mod-logs', type: 'text', staffOnly: true },
            ]},
        ],
        roles: [
            { name: 'DIVIDER_STAFF', color: '#2B2D31', hoist: true, type: 'divider', divLabel: 'Team' },
            { name: 'Owner', color: '#FF0000', hoist: true, type: 'owner' },
            { name: 'Admin', color: '#E74C3C', hoist: true, type: 'admin' },
            { name: 'Moderator', color: '#3498DB', hoist: true, type: 'mod' },
            { name: 'Editor', color: '#E91E63', hoist: true, type: 'staff' },
            { name: 'Support', color: '#2ECC71', hoist: true, type: 'support' },
            { name: 'DIVIDER_FANS', color: '#2B2D31', hoist: true, type: 'divider2', divLabel: 'Fans' },
            { name: 'OG Fan', color: '#F1C40F', hoist: true, type: 'mvp' },
            { name: 'Subscriber', color: '#2ECC71', hoist: true, type: 'vip' },
            { name: 'Fan', color: '#95A5A6', hoist: false, type: 'member' },
            { name: 'Atlas Bypass', color: '#2B2D31', hoist: false, type: 'bypass' },
            { name: 'Bots', color: '#546E7A', hoist: false, type: 'bots' },
        ]
    },
    anime: {
        name: 'Anime Server',
        categories: [
            { name: 'GATE', channels: [
                { name: 'welcome', type: 'text', readOnly: true },
                { name: 'rules', type: 'text', readOnly: true },
                { name: 'self-roles', type: 'text', readOnly: true },
            ]},
            { name: 'NEWS', channels: [
                { name: 'announcements', type: 'text', readOnly: true },
                { name: 'giveaways', type: 'text' },
                { name: 'events', type: 'text', readOnly: true },
            ]},
            { name: 'ANIME', channels: [
                { name: 'anime-chat', type: 'text' },
                { name: 'manga-chat', type: 'text' },
                { name: 'recommendations', type: 'text' },
                { name: 'waifu-husbando', type: 'text' },
                { name: 'fan-art', type: 'text' },
                { name: 'spoilers', type: 'text' },
            ]},
            { name: 'CHILL', channels: [
                { name: 'general', type: 'text' },
                { name: 'off-topic', type: 'text' },
                { name: 'memes', type: 'text' },
                { name: 'media', type: 'text' },
            ]},
            { name: 'FUN', channels: [
                { name: 'bot-commands', type: 'text' },
                { name: 'counting', type: 'text' },
                { name: 'owo', type: 'text' },
            ]},
            { name: 'VOICE', channels: [
                { name: 'Chill Zone', type: 'voice' },
                { name: 'Watch Party', type: 'voice' },
                { name: 'Music', type: 'voice' },
            ]},
            { name: 'STAFF', channels: [
                { name: 'staff-chat', type: 'text', staffOnly: true },
                { name: 'mod-logs', type: 'text', staffOnly: true },
            ]},
        ],
        roles: [
            { name: 'DIVIDER_STAFF', color: '#2B2D31', hoist: true, type: 'divider', divLabel: 'Council' },
            { name: 'Owner', color: '#FF0000', hoist: true, type: 'owner' },
            { name: 'Admin', color: '#E74C3C', hoist: true, type: 'admin' },
            { name: 'Moderator', color: '#3498DB', hoist: true, type: 'mod' },
            { name: 'Support', color: '#2ECC71', hoist: true, type: 'support' },
            { name: 'DIVIDER_RANKS', color: '#2B2D31', hoist: true, type: 'divider2', divLabel: 'Ranks' },
            { name: 'Senpai', color: '#E91E63', hoist: true, type: 'mvp' },
            { name: 'Weeb', color: '#9B59B6', hoist: true, type: 'vip' },
            { name: 'Otaku', color: '#95A5A6', hoist: false, type: 'member' },
            { name: 'Atlas Bypass', color: '#2B2D31', hoist: false, type: 'bypass' },
            { name: 'Bots', color: '#546E7A', hoist: false, type: 'bots' },
        ]
    },
    general: {
        name: 'General Server',
        categories: [
            { name: 'INFO', channels: [
                { name: 'welcome', type: 'text', readOnly: true },
                { name: 'rules', type: 'text', readOnly: true },
            ]},
            { name: 'NEWS', channels: [
                { name: 'announcements', type: 'text', readOnly: true },
            ]},
            { name: 'CHAT', channels: [
                { name: 'general', type: 'text' },
                { name: 'media', type: 'text' },
                { name: 'off-topic', type: 'text' },
            ]},
            { name: 'VOICE', channels: [
                { name: 'General', type: 'voice' },
                { name: 'VC 2', type: 'voice' },
            ]},
            { name: 'BOT', channels: [
                { name: 'bot-commands', type: 'text' },
            ]},
            { name: 'STAFF', channels: [
                { name: 'staff-chat', type: 'text', staffOnly: true },
                { name: 'mod-logs', type: 'text', staffOnly: true },
            ]},
        ],
        roles: [
            { name: 'Owner', color: '#FF0000', hoist: true, type: 'owner' },
            { name: 'Admin', color: '#E74C3C', hoist: true, type: 'admin' },
            { name: 'Moderator', color: '#3498DB', hoist: true, type: 'mod' },
            { name: 'Support', color: '#2ECC71', hoist: true, type: 'support' },
            { name: 'Member', color: '#95A5A6', hoist: false, type: 'member' },
            { name: 'Atlas Bypass', color: '#2B2D31', hoist: false, type: 'bypass' },
            { name: 'Bots', color: '#546E7A', hoist: false, type: 'bots' },
        ]
    },
};

var bigServerExtras = {
    categories: [
        { name: 'SOCIALS', channels: [
            { name: 'self-promo', type: 'text' },
            { name: 'youtube', type: 'text' },
            { name: 'twitch', type: 'text' },
            { name: 'tiktok', type: 'text' },
        ]},
        { name: 'EVENTS', channels: [
            { name: 'giveaways', type: 'text' },
            { name: 'events', type: 'text', readOnly: true },
            { name: 'partnerships', type: 'text', readOnly: true },
            { name: 'booster-perks', type: 'text', readOnly: true },
        ]},
        { name: 'ENGAGE', channels: [
            { name: 'polls', type: 'text' },
            { name: 'confessions', type: 'text' },
            { name: 'starboard', type: 'text', readOnly: true },
            { name: 'server-bump', type: 'text' },
        ]},
        { name: 'EXTRA VC', channels: [
            { name: 'Trio', type: 'voice' },
            { name: 'Squad', type: 'voice' },
            { name: 'Movie Night', type: 'voice' },
        ]},
    ],
    extraRoles: [
        { name: 'Partner', color: '#1ABC9C', hoist: true, type: 'partner' },
        { name: 'Booster', color: '#F47FFF', hoist: true, type: 'booster' },
        { name: 'OG', color: '#FFD700', hoist: true, type: 'og' },
        { name: 'Color: Red', color: '#FF0000', hoist: false, type: 'color_red' },
        { name: 'Color: Blue', color: '#3498DB', hoist: false, type: 'color_blue' },
        { name: 'Color: Green', color: '#2ECC71', hoist: false, type: 'color_green' },
        { name: 'Color: Pink', color: '#E91E63', hoist: false, type: 'color_pink' },
        { name: 'Color: Purple', color: '#9B59B6', hoist: false, type: 'color_purple' },
        { name: 'Color: Orange', color: '#E67E22', hoist: false, type: 'color_orange' },
        { name: 'Announcements Ping', color: '#2B2D31', hoist: false, type: 'ping_announce' },
        { name: 'Giveaway Ping', color: '#2B2D31', hoist: false, type: 'ping_giveaway' },
        { name: 'Event Ping', color: '#2B2D31', hoist: false, type: 'ping_event' },
    ]
};

var welcomeMessages = [
    { id: 'w1', label: 'Classic', message: '# Welcome to {server}! \n\nHey {user}! We are so glad to have you here! You are our **{count}th** member!\n\n> Make sure to read the rules and have fun!' },
    { id: 'w2', label: 'Cool & Modern', message: '## Yo {user}! \n\nWelcome to **{server}**! Member **#{count}**!\n\n> Check out rules\n> Grab roles\n> Start chatting!\n\nEnjoy your stay!' },
    { id: 'w3', label: 'Formal', message: '## Welcome, {user}\n\nWe are pleased to welcome you to **{server}**.\nMember **{count}**.\n\n> Please review our rules.' },
    { id: 'w4', label: 'Hype', message: '# LETS GOOO! \n\n{user} just landed in **{server}**! \nMember **#{count}**!\n\n> Drop a message and say hi!' },
    { id: 'w5', label: 'Gaming', message: '# Player Joined! \n\n{user} entered the server!\n**{server}** - Player **#{count}**\n\n> Pick your games\n> Join voice\n> Compete!' },
    { id: 'w6', label: 'Minimal', message: 'Welcome {user}' },
    { id: 'w7', label: 'Anime', message: '# Welcome {user}-san! \n\nMember #{count} desu~\n\n> Check anime channels\n> Share fan art\n> Join watch parties' },
    { id: 'w8', label: 'Royal', message: '# All Hail {user}! \n\nThe **{count}th** member has arrived!\n\n> Your throne awaits.' },
    { id: 'w9', label: 'Cozy', message: '## Hey {user}! \n\nGrab coffee and chill in **{server}**!\nMember **#{count}**' },
    { id: 'w10', label: 'Alert', message: '# NEW MEMBER ALERT \n\n{user} breached **{server}**!\nIntruder **#{count}**!\n\n> Access granted.' },
    { id: 'w11', label: 'Selling', message: '## Welcome to {server}! \n\n{user} - Member **#{count}**\n\n> Check services\n> Open ticket to order\n> Leave a review' },
    { id: 'w12', label: 'Creator', message: '# {user} joined the fam! \n\nFan **#{count}**!\n\n> Turn on notis\n> Share fan art\n> Watch clips' },
];

var ticketDescriptions = [
    { id: 'td1', label: 'General Support', desc: 'I need help with something general' },
    { id: 'td2', label: 'Report a User', desc: 'I want to report someone for breaking rules' },
    { id: 'td3', label: 'Bug Report', desc: 'I found a bug or issue' },
    { id: 'td4', label: 'Purchase/Order', desc: 'I want to make a purchase or inquiry' },
    { id: 'td5', label: 'Partnership', desc: 'I want to partner with this server' },
    { id: 'td6', label: 'Appeal', desc: 'I want to appeal a punishment' },
    { id: 'td7', label: 'Suggestion', desc: 'I have a suggestion for the server' },
    { id: 'td8', label: 'Other', desc: 'Something else not listed' },
];

module.exports = { serverTemplates, bigServerExtras, welcomeMessages, ticketDescriptions };
